module.exports = {
    someSidebar: {
        Discover: [
            'getting-started/getting-started',
            'getting-started/install-configure',
            'getting-started/react-integration',
            'getting-started/stylable-intelligence',
        ],
        Guides: [
            'guides/components-basics',
            'guides/component-best-practices',
            'guides/runtime',
            'guides/stylable-application',
            'guides/stylable-component-library',
            'guides/project-commons',
            'guides/shared-classes',
            'guides/component-variants',
            'guides/ssr',
            'guides/migration-v3',
        ],
        'Specification Reference': [
            'references/cheatsheet',
            'references/imports',
            'references/root',
            'references/class-selectors',
            'references/tag-selectors',
            'references/extend-stylesheet',
            'references/pseudo-classes',
            'references/pseudo-elements',
            'references/global-selectors',
            'references/custom-selectors',
            'references/mixins',
            'references/formatters',
            'references/st-variables',
            'references/css-vars',
            'references/st-scope',
            'references/namespace',
            'references/using-external-assets',
            'references/keyframes',
        ],
        Credits: ['image-credits']
    },
};