module.exports = {
  Discover: [
    'getting-started/intro',
    'getting-started/install-configure',
    'getting-started/react-integration',
    'getting-started/typescript-integration',
    'getting-started/storybook-integration',
    'getting-started/nextjs-integration',
    'getting-started/stylable-intelligence',
  ],
  Guides: [
    'guides/components-basics',
    'guides/component-best-practices',
    'guides/runtime',
    'guides/stylable-application',
    'guides/stylable-component-library',
    'guides/project-commons',
    'guides/shared-classes',
    'guides/component-variants',
    'guides/ssr',
    'guides/migration-v3',
    'guides/migration-v5',
  ],
  'Specification Reference': [
    'references/cheatsheet',
    'references/imports',
    'references/root',
    'references/class-selectors',
    'references/tag-selectors',
    'references/extend-stylesheet',
    'references/pseudo-classes',
    'references/state-parameter-types',
    'references/pseudo-elements',
    'references/global-selectors',
    'references/custom-selectors',
    'references/mixins',
    'references/formatters',
    'references/st-variables',
    'references/css-vars',
    'references/st-scope',
    'references/namespace',
    'references/using-external-assets',
    'references/keyframes',
    'references/layer',
  ],
};
